### ISSUE TITLE
请问如何设置路径前缀呢？

### ISSUE THREAD

**Issue by VPeterV** [CheckCoder/markdown-image-tool#1]
超赞的插件！！！作者一看就很强，不过请问如何设置图片路径前缀呢？直接修改urlprefix貌似不能设置路径前缀

**Comment by CheckCoder** [comment]
首先感谢 Peter 的使用！
这里面应该存在误解，我在 README 没有说清楚。
这个工具的工作流程是这样的：
1. 获取剪切板中的图片
2. 生成文件名 `cloudFileName`
3. 上传文件，云存储中的文件名就是生成的 `cloudFileName`
4. 粘贴 `![](urlPrefix+cloudFileName+urlSuffix)`

也就是说 `urlPrefix` 是输出链接的前缀，不会影响到文件在云存储中的命名。
我将新增配置字段，来支持设置图片路径前缀的功能。欢迎关注！
